#' Access a workspace
#'
#' @description
#' Provides access to a workspace.
#'
#'
#' @param login [Login-class] Login object generated by either [login_studio()] or [login_testcenter()].
#' @param ws_id Numeric. Workspace id (see URL or call login function with `verbose = TRUE`).
#' @param verbose Logical. If `TRUE`, additional information is printed. Defaults to `FALSE`.
#'
#' @return [Workspace-class] object.
#'
#' @aliases
#' access_workspace,LoginTestcenter-method,LoginStudio-method
#'
#' @export
setGeneric("access_workspace",
           function(login, ws_id = NULL, verbose = FALSE) {
             cli_setting()

             if (is.null(ws_id)) {
               cli::cli_abort("Workspace id, {.ws-id ws_id}, must be defined.", wrap = TRUE)
             }

             ws_ids <-
               login@ws_list %>%
               purrr::map("ws_id") %>%
               unlist()

             if (any(!ws_id %in% ws_ids)) {
               no_ws_id <- setdiff(ws_id, ws_ids)
               cli::cli_abort("Provided {.ws-id ws_id} ({.ws-id {no_ws_id}})
                 does not match any {.ws-id ws_id} of a workspace you have access to.
                 Please check.", wrap = TRUE)
             }

             standardGeneric("access_workspace")
           })

#' @describeIn access_workspace Provide access to selected workspaces after logging in
setMethod("access_workspace",
          signature = signature(login = "LoginStudio"),
          function(login, ws_id, verbose) {
            ws_meta_list <-
              login@wsg_list %>%
              purrr::map(function(wsg) {
                wsg$ws_list %>%
                  purrr::map(function(ws) {
                    ws$wsg_id <- wsg$wsg_id
                    ws$wsg_label <- wsg$wsg_label

                    ws
                  })
              }) %>%
              purrr::list_flatten() %>%
              purrr::keep(function(ws) {
                ws$ws_id %in% ws_id
              })

            ws_meta <-
              ws_meta_list %>%
              purrr::list_transpose()

            Workspace <- new("WorkspaceStudio",
                             login = login,
                             ws_id = as.numeric(ws_meta$ws_id),
                             ws_label = as.character(ws_meta$ws_label),
                             wsg_id = as.numeric(ws_meta$wsg_id),
                             wsg_label = as.character(ws_meta$wsg_label)
            )

            cli::cli_alert_success("IQB Studio workspace successfully accessed.")

            if (verbose) {
              show(Workspace)
            }

            return(Workspace)
          })

#' @describeIn access_workspace Provide access to a selected workspace after logging in
setMethod("access_workspace",
          signature = signature(login = "LoginTestcenter"),
          function(login, ws_id, verbose) {
            ws_meta <-
              login@ws_list %>%
              purrr::keep(function(ws) {
                ws$ws_id == ws_id
              }) %>%
              purrr::list_flatten()

            Workspace <- new("WorkspaceTestcenter",
                             login = login,
                             ws_id = as.numeric(ws_meta$ws_id),
                             ws_label = as.character(ws_meta$ws_label))

            cli::cli_alert_success("IQB Testcenter workspace successfully accessed.")

            if (verbose) {
              show(Workspace)
            }

            return(Workspace)
          })

