#' Adds full source tree to units
#'
#' @param units Tibble holding units retrieved from [get_units()] and prepared within [add_coding_scheme()].
#'
#' @description
#' This function adds the source tree for a unit table generated by calling [get_units()] and enhanced by [add_coding_scheme()]. The `variable_sources` column is extended by all variables that are used to derive the variable in question, including their `variable_id`, `variable_ref`, and `variable_level`.
#'
#' @return A tibble.
#' @keywords internal
add_source_tree <- function(units, filter_has_codes = TRUE) {
  cli_setting()
  # input validation
  units_cols <- c("ws_id", "unit_id", "unit_key", "variable_id", "variable_ref", "variable_level", "variable_source_type", "variable_sources")
  checkmate::assert_tibble(units)
  assert_cols(units, units_cols, "units")
  checkmate::assert_logical(filter_has_codes, len = 1)

  # function
  units_cs <-
    units %>%
    dplyr::distinct(
      ws_id,
      unit_id,
      unit_key,
      variable_id,
      variable_ref,
      variable_level,
      variable_source_type,
      variable_sources
    )

  source_ids <-
    units_cs %>%
    dplyr::distinct(
      unit_key,
      variable_source_id = variable_id,
      variable_source_ref = variable_ref
    )

  units_cs_unnest <-
    units_cs %>%
    tidyr::unnest(variable_sources, keep_empty = TRUE)

  if (tibble::has_name(units_cs_unnest, "variable_source_ref")) {
    units_cs_unnest %>%
      dplyr::left_join(source_ids,
                       by = dplyr::join_by(
                         "unit_key",
                         "variable_source_ref"))
  } else {
    units_cs_unnest %>%
      dplyr::mutate(
        variable_source_id = NA_character_,
        variable_source_ref = NA_character_
      )
  }
  # Add ids
}
