#' Add metadata to units
#'
#' @param units Tibble holding units retrieved from [get_units()].
#'
#' @description
#' This function adds the unit metadata for a unit table generated by calling [get_units()]. Please note that no other operation except for filtering or `add_coding_scheme()` should be applied to the `units`.
#'
#' @return A tibble.
#' @export
add_metadata <- function(units) {
  cli_setting()

  # Conserve attributes
  unit_attributes <- attributes(units)

  if (tibble::has_name(units, "unit_metadata")) {
    units <- read_metadata(units = units)
  }

  unit_items <-
    units %>%
    dplyr::select(
      -dplyr::any_of(c("unit_profiles", "items_profiles"))
    ) %>%
    tidyr::unnest(
      items_list
    ) %>%
    dplyr::mutate(
      unit_has_items = is.na(item_no)
    ) %>%
    # TODO: This could possibly be removed in 2026 (all relevant units should have updated metdata profiles)
    dplyr::rowwise() %>%
    dplyr::mutate(
      unit_has_uuids = dplyr::if_any(dplyr::any_of("item_uuid"), ~ !is.na(.), .default = FALSE)
    ) %>%
    {
      if ("item_uuid" %in% names(.)) {
        dplyr::mutate(., unit_has_uuids = !is.na(item_uuid))
      } else {
        dplyr::mutate(., unit_has_uuids = FALSE)
      }
    } %>%
    dplyr::ungroup()

  # Item metadata
  units_return <-
    unit_items %>%
    add_profile(units, md_profile = "item_md_profile", profiles = "items_profiles", extra_columns = "item_no") %>%
    add_profile(units, md_profile = "unit_md_profile", profiles = "unit_profiles")

  add_attributes <- setdiff(names(unit_attributes), names(attributes(units_return)))
  attributes(units_return) <- c(attributes(units_return), unit_attributes[add_attributes])

  return(units_return)
}


# Adds profiles to all columns if possible
#' @keywords internal
add_profile <- function(unit_items, units, md_profile, profiles, extra_columns = NULL) {
  unit_attributes <- attributes(unit_items)

  ws_settings <- attr(units, "ws_settings")

  if (! (tibble::has_name(units, profiles) & tibble::has_name(ws_settings, md_profile))) {
    cli::cli_alert_danger("Found no column {.field {profiles}} in {.unit-label units} or found no entry {.field {md_profile}} in {.ws-label workspace settings}.")

    if (profiles == "items_profiles") {
      nest_cols <- setdiff(names(units_final), c(names(units), "unit_has_uuids", "unit_has_items"))

      unit_return <- unit_items %>%
        tidyr::nest(item_metadata = dplyr::any_of(nest_cols))

      return(unit_return)
    } else {
      return(unit_items)
    }
  }

  md_profiles <-
    ws_settings %>%
    dplyr::distinct(dplyr::across(dplyr::any_of(md_profile))) %>%
    dplyr::filter(dplyr::if_any(dplyr::any_of(md_profile), function(x) !is.na(x)))

  metadata <-
    md_profiles %>%
    dplyr::mutate(
      dplyr::across(
        dplyr::any_of(md_profile),
        function(x) purrr::map(x, get_metadata_profile),
        .names = "metadata")
    ) %>%
    tidyr::unnest(dplyr::any_of("metadata")) %>%
    tidyr::unnest(dplyr::any_of("data"))

  if (nrow(metadata) == 0) {
    if (profiles == "items_profiles") {
      nest_cols <- setdiff(names(units_final), c(names(units), "unit_has_uuids", "unit_has_items"))

      unit_items %>%
        tidyr::nest(item_metadata = dplyr::any_of(nest_cols)) %>%
        return()
    } else {
      return(unit_items)
    }
  }

  profiles_meta <-
    metadata %>%
    dplyr::select(dplyr::all_of(md_profile), profile_name, profile_type, multiple, value_label) %>%
    tidyr::nest(metadata_levels = c(value_label))

  # TODO: This would produce a bug there are different profiles with
  # same profile_names that are multiple vs. not multiple...
  profiles_single <-
    profiles_meta %>%
    dplyr::filter(!multiple) %>%
    dplyr::pull(profile_name)

  units_meta <-
    units %>%
    dplyr::select(ws_id, unit_id, dplyr::all_of(profiles)) %>%
    tidyr::unnest(dplyr::all_of(profiles), keep_empty = TRUE) %>%
    dplyr::left_join(ws_settings %>% dplyr::select(ws_id, dplyr::all_of(md_profile)), by = dplyr::join_by("ws_id")) %>%
    dplyr::left_join(metadata, by = dplyr::join_by(!!! c("profile_name", "value_id", md_profile))) %>%
    dplyr::mutate(
      value = dplyr::coalesce(value_label, value_text)
    ) %>%
    dplyr::select(dplyr::all_of(c("ws_id", "unit_id", extra_columns, "profile_name", "value"))) %>%
    tidyr::pivot_wider(names_from = profile_name, values_from = value, values_fn = list) %>%
    tidyr::unnest(dplyr::any_of(profiles_single))

  units_final <-
    unit_items %>%
    dplyr::left_join(units_meta,
                     by = dplyr::join_by(!!! c("ws_id", "unit_id", extra_columns)))


  if (profiles == "items_profiles") {
    nest_cols <- setdiff(names(units_final), c(names(units), "unit_has_uuids", "unit_has_items"))

    units_return <-
      units_final %>%
      tidyr::nest(item_metadata = dplyr::any_of(nest_cols))
  } else if (profiles == "unit_profiles") {
    nest_cols <- setdiff(names(units_final), c(names(units), "item_metadata"))

    units_return <-
      units_final %>%
      tidyr::nest(unit_metadata = dplyr::any_of(nest_cols))
  }

  cli::cli_alert_success("Added {md_profile} to {.unit-label units}.")

  attr(units_return, md_profile) <- profiles_meta
  add_attributes <- setdiff(names(unit_attributes), names(attributes(units_return)))
  attributes(units_return) <- c(attributes(units_return), unit_attributes[add_attributes])

  return(units_return)
}
