#' Extract metadata profiles from units with metadata
#'
#' @param units Tibble holding units retrieved from [get_units()] and prepared with [add_metadata()].
#'
#' @description
#' This function extracts the unit metadata profiles of a unit table generated by [add_metadata()]. This can be used for converting character labels to factors.
#'
#' @return A list of three tibbles, `ws_settings`, `unit_md_profile`, and `item_md_profile`.
#' @export
extract_metadata <- function(units) {
  cli_setting()
  # input validation
  checkmate::assert_tibble(units)

  entries <- c("ws_settings", "item_md_profile", "unit_md_profile")
  assert_attrs(units, entries, "units")

  attributes(units)[entries] %>%
    purrr::set_names(c("ws_settings", "item_md_profile", "unit_md_profile"))
}
